[server]
database = "jotfs.db"
enable_versioning = false
avg_chunk_kib = 1024
port = 6776

[store]
path_style = true
disable_ssl = true
endpoint = "localhost:9004"
bucket = "jotfs-test"
region = "eu-west-1"
