language: go

go:
  - 1.14.x

services:
  - docker

before_install:
  - docker pull minio/minio
  - go get -t -v ./...

script:
  - make tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

