language: go

os:
  - linux
  - osx

go:
  - 1.14.x

services:
  - docker

before_install:
  - docker pull minio/minio
  - go get -t -v ./...
  - pyenv global 3.7.1

script:
  - make tests
  - cd simulator && make run

after_success:
  - bash <(curl -s https://codecov.io/bash)
