with open("./internal/db/schema/000_base.sql") as f:
    sql = f.read()

with open("./internal/db/schema.sql.go", "w") as w:
    w.write("// Code generated by /packsql.py -- DO NOT EDIT\n")
    w.write("package db\n\n")
    w.write("const Q_000_Base = `\n")
    w.write(sql)
    w.write("`\n")
