name: docker_push

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          path: /
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jotfs/jotfs
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
